services:
  postgres:
    image: 'postgres:latest'
    container_name: swift_codes_db
    environment:
      - POSTGRES_DB=swift-codes
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: { }